### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by adityabandla** [younglululu/COCACOLA#2]
Hi

I am using the python version, with contig file, abundance and composition profiles as suggested. I get the following error 

Traceback (most recent call last):
File "COCACOLA-python/cocacola.py", line 167, in <module>
assert (shuffled_namelist[contigIdx] in mapObj)
AssertionError

**Comment by younglululu** [comment]
Dear Aditya, 

The assertion here aims to ensure that the abundance profile and the composition profile contains the same set of contigs. I am wondering if you are using both the abundance profile and the composition profile? If so, could you check they contain the same set of contigs? Thanks!

Yang

**Comment by adityabandla** [comment]
Dear Yang

My bad, I realized that the sample headers were not present in the abundance profiles. After fixing it, it seems to go ahead. Waiting for the run to finish!

Sorry for the red herring

Aditya
