### ISSUE TITLE
FragGeneScan takes forever

### ISSUE THREAD

**Issue by adityabandla** [younglululu/COCACOLA#3]
Hi 

The FragGeneScan seems to take forever. I see that FragGeneScan v1.19 is being called. Can I replace it with v1.30, which is supposed to be much faster?

Any reasons why the legacy version is still being used?

Best,

**Comment by younglululu** [comment]
Dear Aditaya, 

In principle, if FragGeneScan v1.30 generates the same output format as v1.19, you could simply replace it. 

The reason why I am using v1.19 is because I borrow the idea from MaxBin 2.0, which uses v1.19.

**Comment by adityabandla** [comment]
Dear Yang

Thanks for the reply. I will give it a shot, as FragGeneScan v1.3 is now recommended in the MaxBin2.2 page

**Comment by younglululu** [comment]
Dear Aditaya,

Thanks for the kind reminder. I will try to upgrade soon.

**Comment by adityabandla** [comment]
Dear Yang

Thanks! I replaced v1.19 with v1.30 and renamed the folder as v1.19. There was a substantial improvement in the speed. Within an hour or two, the seed generation step was over, while it took close to 8-10h using v1.19
